name: Test compilation of program

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install libraries
      run: sudo apt install wiringpi
    - name: check for library
      run: ls -l /usr/include
    - name: make
      run: make
    - name: make clean
      run: make clean
